# Generated by Django 3.2.5 on 2021-10-13 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vip_name', models.CharField(max_length=64, unique=True, verbose_name='会员名称')),
                ('book_name', models.CharField(max_length=500, verbose_name='书籍名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='借阅时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='归还时间')),
                ('status', models.BooleanField(verbose_name='借阅状态')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('update_name', models.CharField(max_length=64, verbose_name='更新人')),
            ],
            options={
                'db_table': 'borrow',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=64, unique=True, verbose_name='分类名')),
                ('branch_summary', models.CharField(max_length=500, verbose_name='分类简介')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_name', models.CharField(max_length=64, verbose_name='更新人')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
            ],
            options={
                'db_table': 'branch',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=64, unique=True, verbose_name='书籍名称')),
                ('author', models.CharField(max_length=64, verbose_name='作者')),
                ('press', models.CharField(max_length=64, verbose_name='出版社')),
                ('book_summary', models.CharField(max_length=500, verbose_name='书籍简介')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_name', models.CharField(max_length=64, verbose_name='更新人')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_web.branch', verbose_name='分类')),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
