# Generated by Django 3.0.6 on 2021-09-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=64, unique=True, verbose_name='书籍名称')),
                ('branch_id', models.IntegerField(max_length=64, verbose_name='分类ID')),
                ('author', models.CharField(max_length=64, verbose_name='作者')),
                ('press', models.CharField(max_length=64, verbose_name='出版社')),
                ('book_summary', models.CharField(max_length=500, verbose_name='书籍简介')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_name', models.CharField(max_length=64, verbose_name='更新人')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='borrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vip_name', models.CharField(max_length=64, unique=True, verbose_name='会员名称')),
                ('book_name', models.CharField(max_length=500, verbose_name='书籍名称')),
                ('borrow_time', models.DateTimeField(verbose_name='借阅时间')),
                ('end_time', models.DateTimeField(verbose_name='归还时间')),
                ('status', models.BooleanField(verbose_name='借阅状态')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_name', models.CharField(max_length=64, verbose_name='更新人')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
            ],
            options={
                'db_table': 'borrow',
            },
        ),
        migrations.CreateModel(
            name='branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=64, unique=True, verbose_name='分类名')),
                ('branch_summary', models.CharField(max_length=500, verbose_name='分类简介')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_name', models.CharField(max_length=64, verbose_name='更新人')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
            ],
            options={
                'db_table': 'branch',
            },
        ),
    ]
