# Generated by Django 3.2.5 on 2021-10-14 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0002_book_borrow_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='branch',
            new_name='branch_id',
        ),
        migrations.AlterField(
            model_name='book',
            name='branch_id',
            field=models.ForeignKey(db_column='branch_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_web.branch', verbose_name='分类'),
        ),
    ]
