# Generated by Django 3.2.5 on 2021-10-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0003_auto_20211014_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='vip_name',
            field=models.CharField(max_length=64, verbose_name='会员名称'),
        ),
    ]
