# Generated by Django 3.2.5 on 2022-01-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0005_auto_20220110_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='最后修改日期'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='借阅时间'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='归还时间'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='最后修改日期'),
        ),
    ]
